### ISSUE TITLE
I didn't know how to contact you about a question that wasn't related to EFCore Power Tools

### ISSUE THREAD

**Issue by KayakFisher205** [ErikEJ/ErikEJ#1]
I know you were working/Help with .Net Core 7 and I ran into an issue with it that I wasn't sure if addressed. I have some SQL tables that use Replication and particularly Merge Transactions. From version 7, I would get the error like 
Server: Msg 334, Level 16, State 1, Line 1
The target table '<Table Name>' of the DML statement
cannot have any enabled triggers if the statement
contains an OUTPUT clause without INTO clause.

I saw things in github like https://github.com/dotnet/efcore/issues/1441 but I never really found anything related to Replication.
I'd like to get going on full testing but I have to revert everything like Microsoft.EntityFrameworkCore versions (running 6.04) and its just a pain since its compiled in Azure and the Nugets are created there.

I didn't know if you could point me in the right direct to look or even if I should post an issue. Any info you can provide would be helpful.

[Merge Insert Trigger.txt](https://github.com/ErikEJ/ErikEJ/files/8845575/Merge.Insert.Trigger.txt)

**Comment by ErikEJ** [comment]
@roji is there any docs on how to opt out of new Update pipeline?

**Comment by roji** [comment]
Yep - simply inform EF Core that the table in question has a trigger by calling HasTrigger():

```c#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Blog>()
        .ToTable(tb => tb.HasTrigger("TriggerName"));
}
```

(the actual name doesn't matter at this point, since EF doesn't actually try to create the trigger - but that may change in the future)

**Comment by KayakFisher205** [comment]
How would that work using EFCore Power Tools? If you haven't added anything could it be in the config.json file like
 "Tables": [
      {
         "Name": "[dbo].[INT_CCM_HEAT_REPORT]",
         "ObjectType": 0
"HasTrigger":true
      },

I suspect this is a better question to post in EF Core Tools. If so, let me know.

**Comment by ErikEJ** [comment]
@KayakFisher205 It should be part of the model generated.

@roji Any plans to reverse engineer this knowledge (happy to do a PR) - otherwise this change will be quite breaking for database first...

**Comment by roji** [comment]
@ErikEJ good suggestion, opened https://github.com/dotnet/efcore/issues/28185 to track.

**Comment by KayakFisher205** [comment]
I have EF Core Power Tools 2.5.1003.0 and I'm not sure how to implement the HasTrigger function. EF C
The section that the Tool create is below and I manually added the HasTrigger.  Would I have to add that line each time? There are 3 triggers (Insert, Update, Delete). Would I need to add all 3?

 modelBuilder.Entity<TT_EXTRACTION_JOBS>(entity =>
            {
                entity.HasKey(e => e.JOB_COUNTER)
                    .HasName("PK__TT_EXTRA__B560CC9154848F96");

                entity.Property(e => e.JOB_COUNTER).ValueGeneratedNever();

                entity.Property(e => e.REQ_DATE).HasDefaultValueSql("(getdate())");

                entity.Property(e => e.TT_TABLE).HasDefaultValueSql("(' ')");
                entity.ToTable(f => f.HasTrigger("MSmerge_del_444E602D51024904A73A8FA80397FA17"));
            });

**Comment by ErikEJ** [comment]
Just add 1. Name is irrelevant. NOTICE that EF Core Power Tools does nit support EF Core 7 at the moment   so you are on your own

**Comment by KayakFisher205** [comment]
Thanks for the Help. Its just one table and typically that database structure doesn't change so maybe I'll remember to add.

**Comment by ErikEJ** [comment]
Add a unit test to inspect if HasTriggers has been set on your model?
